services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-tico
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
